Pulsed mb
kaelyndunnell/hisp pull request #12
Opened 2024-10-15 21:40 UTC by kaelyndunnell

Added pulses fluxes and temperatures. Integrated with DINA data. Added recombination BC on surface.

2024-10-15 23:21 UTC, RemDelaporteMathurin requested changes

2024-10-15 23:21 UTC, RemDelaporteMathurin commented on environment.yml
>    - fenics-dolfinx=0.8.0
Can You upgrade this to 0.9?

2024-10-15 23:21 UTC, RemDelaporteMathurin commented on environment.yml
> +    - git+https://github.com/remdelaportemathurin/FESTIM@surface-reactions
You may want to pin a specific commit

2024-10-15 23:21 UTC, RemDelaporteMathurin commented on simple_mb.py
> +class FluxFromSurfaceReaction(F.SurfaceFlux):
If you don't use this class please remove it

2024-10-15 23:21 UTC, RemDelaporteMathurin commented on simple_mb.py
> +lines = lines[1:]
You should use numpy genfromtext function instead of this

2024-10-15 23:21 UTC, RemDelaporteMathurin commented on simple_mb.py
> +    E_D=0.39,
This is not @ehodille but from Frauenfeldeer, we have this property in HTM

2024-10-16 06:57 UTC, RemDelaporteMathurin commented on environment.yml
You need to add matplotlib as a conda dependency. This is what is making the Ci fail. Here, matplotlib is installed alongside HTM as a pip package. This conflicts with dolfinx which is installed with Conda.

(hello @shimwell)

2024-10-16 20:58 UTC, kaelyndunnell commented
Solves issue #7 , issue #8 , issue  #9 , and issue #10

2024-10-16 20:58 UTC, merged